#!/bin/sh
#$Id:  $

# <p><b>License and Copyright: </b>The contents of this file will be subject to the
# same open source license as the Fedora Repository System at www.fedora-commons.org
# Copyright &copy; 2006, 2007, 2008 by The Technical University of Denmark.
# All rights reserved.</p>

# @author  gsp@dtv.dk
# @version 

# This script is in the fedoragsearch distribution 
# in WEBSERVER/webapps/fedoragsearch/client
# together with the testEngine script.

# This script assumes that the testEngine script is available
# and set to run on a Fedora repository,
# where the Fedora demo objects have been ingested.

# Expected test results are assumed to be in $TESTHOME/expected/$0,
# see testEngine for further information.
# Expected test results are generated with MODE=expected,
# you have to check that they are as expected, before running against them.

MODE=$1
. ./testEngine $MODE
user_pass fedoraAdmin

begin_suite runRESTClient.sh "test of search result filtering"


run_test_ok "<h2>gfindObjects</h2>" configure configDemoSearchResultFiltering
run_test_ok "<h2>gfindObjects</h2>" configure configDemoSearchResultFiltering fedoragsearch.searchResultFilteringType presearch
run_test_ok "docCount=\"0\"" updateIndex createEmpty
run_test_ok "docCount=\"25\"" updateIndex fromFoxmlFiles
run_test_ok "hitTotal=\"20\"" gfindObjects "image OR smiley"
user_pass smileyAdmin1
run_test_ok "hitTotal=\"13\"" gfindObjects "image OR smiley"
user_pass smileyUser1
run_test_ok "hitTotal=\"12\"" gfindObjects "image OR smiley"
run_test_ok "<h2>gfindObjects</h2>" configure configDemoSearchResultFiltering fedoragsearch.searchResultFilteringType insearch
user_pass fedoraAdmin
run_test_ok "hitTotal=\"20\"" gfindObjects "image OR smiley"
user_pass smileyAdmin1
run_test_ok "hitTotal=\"13\"" gfindObjects "image OR smiley"
user_pass smileyUser1
run_test_ok "hitTotal=\"12\"" gfindObjects "image OR smiley"
run_test_ok "<h2>gfindObjects</h2>" configure configDemoSearchResultFiltering fedoragsearch.searchResultFilteringType postsearch
user_pass fedoraAdmin
run_test_ok "hitsDenied=\"0\"" gfindObjects "image OR smiley" AllObjectsIndex 1 20
user_pass smileyAdmin1
run_test_ok "hitsDenied=\"7\"" gfindObjects "image OR smiley" AllObjectsIndex 1 20
user_pass smileyUser1
run_test_ok "hitsDenied=\"8\"" gfindObjects "image OR smiley" AllObjectsIndex 1 20

#errors found

user_pass unknownUser
run_test_error "HTTP response code: 401" 	gfindObjects "image OR smiley"

end_suite
