#!/bin/sh
#$Id: testDemoOnLucene 5719 2006-10-13 14:17:53Z gertsp $

# <p><b>License and Copyright: </b>The contents of this file will be subject to the
# same open source license as the Fedora Repository System at www.fedora-commons.org
# Copyright &copy; 2006, 2007, 2008 by The Technical University of Denmark.
# All rights reserved.</p>

# @author  gsp@dtv.dk
# @version 

# This script is in the fedoragsearch distribution 
# in WEBSERVER/webapps/fedoragsearch/client
# together with the testEngine script.

echo "test setup"
echo "- creating new fedora repository and Gsearch index on 24 demo objects"
echo "- assuming fedora.fcfg has"
echo "  - server on localhost:8080"
echo "  - localMySQLPool as datastore"

HOST=$1
PORT=$2
TESTDB=$FEDORA_HOME/demotest

$FEDORA_HOME/tomcat/bin/shutdown.sh

rm -r $FEDORA_HOME/data/datastreams/*
rm -r $FEDORA_HOME/data/objects/*

echo "drop database $TESTDB;" | mysql -u root
echo "create database $TESTDB;" | mysql -u root
echo "grant all on $TESTDB.* to fedoraAdmin@localhost identified by 'fedoraAdmin';" | mysql -u root
echo "grant all on $TESTDB.* to fedoraAdmin@'%' identified by 'fedoraAdmin';" | mysql -u root

$FEDORA_HOME/tomcat/bin/startup.sh

echo "sh runRESTClient.sh $HOST:$PORT configure configDemoOnLucene > /dev/null"
sh runRESTClient.sh $HOST:$PORT configure configDemoOnLucene > /dev/null

echo "sh runRESTClient.sh $HOST:$PORT updateIndex createEmpty > /dev/null"
sh runRESTClient.sh $HOST:$PORT updateIndex createEmpty > /dev/null

$FEDORA_HOME/client/bin/fedora-ingest-demos.sh $HOST $PORT fedoraAdmin fedoraAdmin http
#
# if fedora.fcfg specifies GSearch, then ingest-demos will include indexing
# if not, run updateIndex as below
# 
#echo "sh runRESTClient.sh $HOST:$PORT updateIndex fromFoxmlFiles > /dev/null"
#sh runRESTClient.sh $HOST:$PORT updateIndex fromFoxmlFiles > /dev/null
