#!/bin/sh
#$Id: testDemoOnLucene 5719 2006-10-13 14:17:53Z gertsp $

# <p><b>License and Copyright: </b>The contents of this file will be subject to the
# same open source license as the Fedora Repository System at www.fedora.info
# It is expected to be released with Fedora version 2.2.

# Copyright &copy; 2006 by The Technical University of Denmark.
# All rights reserved.</p>

# @author  gsp@dtv.dk
# @version 

# This script is in the fedoragsearch distribution 
# in WEBSERVER/webapps/fedoragsearch/client
# together with the testEngine script.

# This script assumes that the testEngine script is available
# and set to run on a Fedora repository,
# where the Fedora demo objects have been ingested.

# Expected test results are assumed to be in $TESTHOME/expected/$0,
# see testEngine for further information.
# Expected test results are generated with MODE=expected,
# you have to check that they are as expected, before running against them.

export HOST=localhost
export PORT=8989

MODE=$1
. ./testEngine $MODE

echo "sh runRESTClient.sh $HOST:$PORT configure configTestOnLucene > /dev/null"
sh runRESTClient.sh $HOST:$PORT configure configTestOnLucene > /dev/null

begin_suite runRESTClient.sh "test of truncated special characters"

$FEDORA_HOME/client/bin/fedora-purge.sh $HOST:$PORT fedoraAdmin fedoraAdmin test:truncation http purging
$FEDORA_HOME/client/bin/fedora-ingest.sh file "test_truncation.xml" "foxml1.0" $HOST:$PORT fedoraAdmin fedoraAdmin http "ingesting test_truncation object"

run_test gfindObjects "dc.description:éèñô"
run_test gfindObjects "dc.description:father&son"
run_test gfindObjects "dc.description:haven't"
run_test gfindObjects "dc.description:f&s"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=20"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=19"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=18"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=17"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=16"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=15"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=14"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=13"
run_test "?operation=gfindObjects&query=dc.description:f%26s&fieldMaxLength=12"

#errors found


end_suite
