#!/bin/sh
#$Id$

# <p><b>License and Copyright: </b>The contents of this file will be subject to the
# same open source license as the Fedora Repository System at www.fedora-commons.org
# Copyright &copy; 2006, 2007, 2008 by The Technical University of Denmark.
# All rights reserved.</p>

# @author  gsp@dtv.dk
# @version 

# This script is in the fedoragsearch distribution in WEBSERVER/webapps/fedoragsearch/client
# together with a set of test suite scripts.

# This script assumes that a Fedora repository is running on HOSTPORT.

# The TESTHOME dir is assumed to contain expected test results in $TESTHOME/expected/$SUITE

# The script is sourced from a test suite script, installed in the same directory.
# The SUITE name is given by the calling script name.

# Each test suite script in the fedoragsearch distribution has expected test results with it.

# The client program name is given as parameter to begin_suite().
# it must be installed in the same directory.

# Two client programs are in the fedoragsearch distribution: RESTClient and SOAPClient,
# they can be called with runRESTClient.sh and runSOAPClient.sh,
# they can be found in WEBSERVER/webapps/fedoragsearch/client, and should be called from there.

# When MODE="expected" then test run results will appear in $TESTHOME/expected/$SUITE
# When MODE="" then
#   Test run results will appear in $TESTHOME/result/$SUITE
#   Test results will appear in $TESTHOME/diff/$SUITE as the diff between expected and result.
#   Diff count will come out of end_suite().

HOSTPORT=$HOST:$PORT
if [ $HOSTPORT = ":" ] ; then
    export HOST=localhost
    export PORT=8080
    HOSTPORT=$HOST:$PORT
fi;
TESTHOME=.
SUITE=$0
MODE=$1

get_timestamp(){
    echo "`date '+20%y-%m-%d %T'`"
}

usage(){
    echo "Usage:"
    echo "    sh $0 [expected | verbose]"
}

run_test(){
    TESTCOUNT=`expr $TESTCOUNT "+" 1`
    if [ "$MODE" = "expected" -o "$MODE" = "verbose" ] ; then
    	echo "<`get_timestamp`>run_test() #$TESTCOUNT $CLIENT $1 $2 $3 $4 $5 $6 $7 $8 $9 "
    fi;
    FILENAME=$CLIENT.$TESTCOUNT
    if [ "$MODE" = "expected" ] ; then
        sh $CLIENT $HOSTPORT "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" > $TESTHOME/expected/$SUITE/$FILENAME
    else
    if [ "$1" != "configure" ] ; then
        sh $CLIENT $HOSTPORT "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" > $TESTHOME/result/$SUITE/$FILENAME 2>&1
        diff -I.*milliseconds.* -I.*resultPage.* -I.*cvsDate.* -I.*createdDate.* -I.*lastModifiedDate.* -I.*$HttpInputStream@.* $TESTHOME/expected/$SUITE/$FILENAME $TESTHOME/result/$SUITE/$FILENAME > $TESTHOME/diff/$SUITE/$FILENAME
        if [ ! `cat $TESTHOME/diff/$SUITE/$FILENAME | wc -c` = 0 ] ; then 
            DIFFCOUNT=`expr $DIFFCOUNT "+" 1`
            echo " "
            echo "<`get_timestamp`>!!! DIFF#$DIFFCOUNT >>>"
                cat $TESTHOME/diff/$SUITE/$FILENAME
            echo "<`get_timestamp`>!!! DIFF#$DIFFCOUNT <<<"
            echo " "
        fi;
    fi;
    fi;
}

run_test_ok(){
    TESTCOUNT=`expr $TESTCOUNT "+" 1`
    EXPECTED_OK_PATTERN=$1
    if [ "$MODE" = "expected" -o "$MODE" = "verbose" ] ; then
    	echo "<`get_timestamp`>run_test_ok() #$TESTCOUNT $CLIENT $EXPECTED_OK_PATTERN $2 $3 $4 $5 $6 $7 $8 $9 "
    fi;
    FILENAME=$CLIENT.$TESTCOUNT
    if [ "$MODE" = "expected" ] ; then
        sh $CLIENT $HOSTPORT "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" > $TESTHOME/expected/$SUITE/$FILENAME
    else
        sh $CLIENT $HOSTPORT "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" > $TESTHOME/result/$SUITE/$FILENAME 2>&1
    	OKLINE=`egrep "$EXPECTED_OK_PATTERN" "$TESTHOME/result/$SUITE/$FILENAME"`
        if [ -z "$OKLINE" ] ; then 
        		echo " "
                DIFFCOUNT=`expr $DIFFCOUNT "+" 1`
                echo "!!! DIFF#$DIFFCOUNT >>>"
    	        echo "<`get_timestamp`>run_test_ok() #$TESTCOUNT $CLIENT $EXPECTED_OK_PATTERN $2 $3 $4 $5 $6 $7 $8 $9 "
                echo "EXPECTED_OK_PATTERN=$EXPECTED_OK_PATTERN not found in result in $TESTHOME/result/$SUITE/$FILENAME"
                echo "EXPECTED_OK_PATTERN=$EXPECTED_OK_PATTERN not found in result=" > $TESTHOME/diff/$SUITE/$FILENAME
                cat $TESTHOME/result/$SUITE/$FILENAME > $TESTHOME/diff/$SUITE/$FILENAME
                echo "!!! DIFF#$DIFFCOUNT <<<"
        		echo " "
        else
    		if [ "$MODE" = "verbose" ] ; then
        		echo " "
    			echo "OKLINE=$OKLINE"
        		echo " "
        	fi;
        fi;
    fi;
}

run_test_error(){
    TESTCOUNT=`expr $TESTCOUNT "+" 1`
    EXPECTED_ERROR_PATTERN=$1
    if [ "$MODE" = "expected" -o "$MODE" = "verbose" ] ; then
    	echo "<`get_timestamp`>run_test_error() #$TESTCOUNT $CLIENT $EXPECTED_ERROR_PATTERN $2 $3 $4 $5 $6 $7 $8 $9 "
    fi;
    FILENAME=$CLIENT.$TESTCOUNT
    if [ "$MODE" = "expected" ] ; then
        sh $CLIENT $HOSTPORT "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" > $TESTHOME/expected/$SUITE/$FILENAME
    else
        sh $CLIENT $HOSTPORT "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" > $TESTHOME/result/$SUITE/$FILENAME 2>&1
    	ERRORLINE=`grep "$EXPECTED_ERROR_PATTERN" "$TESTHOME/result/$SUITE/$FILENAME"`
        if [ -z "$ERRORLINE" ] ; then 
        		echo " "
                DIFFCOUNT=`expr $DIFFCOUNT "+" 1`
                echo "!!! DIFF#$DIFFCOUNT >>>"
    	        echo "<`get_timestamp`>run_test_error() #$TESTCOUNT $CLIENT $EXPECTED_OK_PATTERN $2 $3 $4 $5 $6 $7 $8 $9 "
                echo "EXPECTED_ERROR_PATTERN=$EXPECTED_ERROR_PATTERN not found in result in $TESTHOME/result/$SUITE/$FILENAME"
                echo "EXPECTED_ERROR_PATTERN=$EXPECTED_ERROR_PATTERN not found in result=" > $TESTHOME/diff/$SUITE/$FILENAME
                cat $TESTHOME/result/$SUITE/$FILENAME > $TESTHOME/diff/$SUITE/$FILENAME
                echo "!!! DIFF#$DIFFCOUNT <<<"
        		echo " "
        else
    		if [ "$MODE" = "verbose" ] ; then
        		echo " "
    			echo "ERRORLINE=$ERRORLINE"
        		echo " "
        	fi;
        fi;
    fi;
}

begin_suite(){
    CLIENT=$1
    TESTCOUNT=0
    DIFFCOUNT=0
    echo "<`get_timestamp`>begin_suite $1 \"$2"\"
}

user_pass(){
    if [ ! -z "$1" ] ; then 
        fgsUserName=$1
        fgsPassword=$2
        if [ -z "$fgsPassword" ] ; then 
            fgsPassword=$fgsUserName
        fi;
    else
        if [ -z "$fgsUserName" ] ; then 
            echo -n "GSearch user name: "
            read fgsUserName
            echo -n "Password: "
            stty -echo
            read fgsPassword
            stty echo
            if [ -z "$fgsPassword" ] ; then 
                fgsPassword=$fgsUserName
            fi;
            echo ""
        fi;
    fi;
    export fgsUserName
    export fgsPassword
}

end_suite(){
    echo "<`get_timestamp`>TESTCOUNT=$TESTCOUNT"
    if [ ! "$MODE" = "expected" ] ; then
    	echo "<`get_timestamp`>DIFFCOUNT=$DIFFCOUNT"
    fi;
    echo "<`get_timestamp`>end_suite"
}

echo "<`get_timestamp`>testEngine $*"

if [ $# -gt 1 ] ; then
    usage
    exit 1
fi;

if [ $# -eq 1 ] ; then
    if [ ! \( "$MODE" = "expected" -o "$MODE" = "verbose" \) ] ; then
        usage
        exit 1
    fi;
fi;

if [ ! -d $TESTHOME/expected ] ; then
    mkdir $TESTHOME/expected
fi;
if [ "$MODE" = "expected" ] ; then
    if [ -d $TESTHOME/expected/$SUITE ] ; then
        rm -r $TESTHOME/expected/$SUITE
    fi;
    mkdir $TESTHOME/expected/$SUITE
fi;

if [ ! -d $TESTHOME/result ] ; then
    mkdir $TESTHOME/result
fi;
if [ -d $TESTHOME/result/$SUITE ] ; then
    rm -r $TESTHOME/result/$SUITE
fi;
mkdir $TESTHOME/result/$SUITE

if [ ! -d $TESTHOME/diff ] ; then
    mkdir $TESTHOME/diff
fi;
if [ -d $TESTHOME/diff/$SUITE ] ; then
    rm -r $TESTHOME/diff/$SUITE
fi;
mkdir $TESTHOME/diff/$SUITE
