#!/bin/sh
#$Id$

# <p><b>License and Copyright: </b>The contents of this file will be subject to the
# same open source license as the Fedora Repository System at www.fedora.info
# It is expected to be released with Fedora version 2.2.

# Copyright &copy; 2006 by The Technical University of Denmark.
# All rights reserved.</p>

# @author  gsp@dtv.dk
# @version 

# The script assumes that the testEngine script is available
# and set to run on a Fedora repository,
# where the Fedora demo objects have been ingested.
# Further, expected test results are assumed to be in ./expected/$0

. ./testEngine $1

begin_suite runRESTClient.sh

run_test configure configDemoOnLucene
run_test getRepositoryInfo
run_test getIndexInfo
run_test updateIndex createEmpty
run_test updateIndex fromPid demo:10
run_test updateIndex fromFoxmlFiles
run_test browseIndex a dc.title
run_test gfindObjects fedora

end_suite

begin_suite runSOAPClient.sh

run_test getRepositoryInfo
run_test getIndexInfo
run_test updateIndex createEmpty
run_test updateIndex fromPid demo:11
run_test updateIndex fromFoxmlFiles
run_test browseIndex a dc.title
run_test gfindObjects fedora

end_suite
