#!/bin/sh
#$Id: testDemoOnLucene 5719 2006-10-13 14:17:53Z gertsp $

# <p><b>License and Copyright: </b>The contents of this file will be subject to the
# same open source license as the Fedora Repository System at www.fedora-commons.org
# Copyright &copy; 2006, 2007, 2008 by The Technical University of Denmark.
# All rights reserved.</p>

# @author  gsp@dtv.dk
# @version 

# This script is in the fedoragsearch distribution 
# in WEBSERVER/webapps/fedoragsearch/client
# together with the testEngine script.

# This script assumes that the testEngine script is available
# and set to run on a Fedora repository,
# where the Fedora demo objects have been ingested.

# Expected test results are assumed to be in $TESTHOME/expected/$0,
# see testEngine for further information.
# Expected test results are generated with MODE=expected,
# you have to check that they are as expected, before running against them.

MAX=$1

echo "sh runRESTClient.sh $HOST:$PORT configure configTestOnLucene > /dev/null"
sh runRESTClient.sh $HOST:$PORT configure configTestOnLucene > /dev/null

while [ $MAX -gt 0 ]
do
MAX=`expr $MAX - 1`
$FEDORA_HOME/client/bin/fedora-ingest.sh file "test_obj_demo_11.xml" "foxml1.0" $HOST:$PORT fedoraAdmin fedoraAdmin http "ingesting test_multiple_ingest object"
done
