#!/bin/sh
#$Id: testDemoOnLucene 5719 2006-10-13 14:17:53Z gertsp $

# <p><b>License and Copyright: </b>The contents of this file will be subject to the
# same open source license as the Fedora Repository System at www.fedora.info
# It is expected to be released with Fedora version 2.2.

# Copyright &copy; 2006 by The Technical University of Denmark.
# All rights reserved.</p>

# @author  gsp@dtv.dk
# @version 

# This script is in the fedoragsearch distribution 
# in WEBSERVER/webapps/fedoragsearch/client
# together with the testEngine script.

# This script assumes that the testEngine script is available
# and set to run on a Fedora repository,
# where the Fedora demo objects have been ingested.

# Expected test results are assumed to be in $TESTHOME/expected/$0,
# see testEngine for further information.
# Expected test results are generated with MODE=expected,
# you have to check that they are as expected, before running against them.

MODE=$1
. ./testEngine $MODE

begin_suite runRESTClient.sh "test of sortFields parameter for gfindObjects"

#    sortFields ::= [sortField[';'sortField]*]
#    sortField  ::= sortFieldName[','(sortType | locale)[','reverse]]]]
#    sortFieldName ::= #the name of an index field, which is UN_TOKENIZED and contains a single term per document
#    sortType   ::= 'AUTO' (default) | 'DOC' | 'SCORE' | 'INT' | 'FLOAT' | 'STRING'
#    locale     ::= language['-'country['-'variant]]
#    reverse    ::= 'false' (default) | 'true'

#host:port gfindObjects query [indexName [hitPageStart [hitPageSize [snippetsMax [fieldMaxLength [sortFields [resultPageXslt]]]]]]]

run_test configure configDemoOnLucene
run_test gfindObjects image
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,AUTO
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,AUTO,true
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,DOC
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,SCORE
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,INT
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,FLOAT
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,STRING
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,cy
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,cy-GB
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,cy-GB-var
run_test gfindObjects image DemoOnLucene 1 10 3 50 "fgs.createdDate"
run_test gfindObjects image DemoOnLucene 1 10 3 50 "fgs.createdDate,AUTO,true"
run_test gfindObjects image DemoOnLucene 1 10 3 50 "PID;fgs.createdDate"
run_test configure configDemoOnLucene defaultSortFields PID
run_test gfindObjects image
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,SCORE,true
run_test configure configDemoOnLucene defaultSortFields PID,SCORE,true
run_test gfindObjects image
run_test gfindObjects image DemoOnLucene 1 10 3 50 PID,SCORE

#errors found

run_test_error "not found as index field" 	gfindObjects image DemoOnLucene 1 10 3 50 "nonexistingfield"
run_test_error "empty sortField" 			gfindObjects image DemoOnLucene 1 10 3 50 "PID;+;+"
run_test_error "empty sortFieldName" 		gfindObjects image DemoOnLucene 1 10 3 50 "+,+"
run_test_error "empty sortType or locale" 	gfindObjects image DemoOnLucene 1 10 3 50 "PID,+,+"
run_test_error "unknown sortType" 			gfindObjects image DemoOnLucene 1 10 3 50 "PID,UNKNOWN"
run_test_error "unknown locale" 			gfindObjects image DemoOnLucene 1 10 3 50 "PID,aa-BB-var-xyz"
run_test_error "empty language" 			gfindObjects image DemoOnLucene 1 10 3 50 "PID,-+-GB"
run_test_error "unknown language" 			gfindObjects image DemoOnLucene 1 10 3 50 "PID,unknown"
run_test_error "empty country" 				gfindObjects image DemoOnLucene 1 10 3 50 "PID,cy-+-+"
run_test_error "empty variant" 				gfindObjects image DemoOnLucene 1 10 3 50 "PID,cy-GB-+-"
run_test_error "unknown reverse" 			gfindObjects image DemoOnLucene 1 10 3 50 "PID,cy,noreverse"
run_test_error "sortFields must be UN_TOKENIZED" gfindObjects image DemoOnLucene 1 10 3 50 "dc.description"

end_suite
